export const PLAY_BUTTON_CLICK = "PLAY_BUTTON_CLICK";
export const NUMBER_OF_CARDS_SELECTED = "NUMBER_OF_CARDS_SELECTED";
export const NUMBER_OF_CARDS_SELECTION_CONFIRMATION = "NUMBER_OF_CARDS_SELECTION_CONFIRMATION";